<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.6">
  <POU Name="FB_PRP" Id="{9fd9a9ff-7fc2-4c41-a012-ab4bc4e66739}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PRP
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>